// home
export const HOME_DATA_REQUESTING = 'HOME_DATA_REQUESTING'
export const FETCH_HOME_INIT_DATA_SUCCESS = 'FETCH_HOME_INIT_DATA_SUCCESS'
export const FETCH_HOME_MORE_DATA_SUCCESS = 'FETCH_HOME_MORE_DATA_SUCCESS'


